from enum import Enum
import numpy as np


class CommunicationHeaderObjectType(Enum):
    FUNCTION = 0
    NUM_BUFFERS_REQUIRED = 1
    NUM_BYTES = 2
    DATA_STRUCTURE = 3
    BYTES_PER_ELEMENT = 4
    DATA_TYPE = 5
    NUM_CHANNELS = 6
    NUM_ELEMENTS = 7
    HAS_COLOR = 8
    HAS_POINT_SIZES = 9
    NUM_VERTICES = 10
    NUM_INDICES = 11
    NUM_OBJECTS = 12
    DIMENSION_2D = 13
    HAS_PAYLOAD = 14
    AZIMUTH = 15
    ELEVATION = 16
    AXIS_MIN_MAX_VEC = 17
    VEC3 = 18
    SCALE_MATRIX = 19
    TRANSLATION_VECTOR = 20
    ROTATION_MATRIX = 21
    PROJECT_FILE_NAME = 22
    TITLE_STRING = 23
    POS2D = 24
    FIGURE_NUM = 25
    PARENT_NAME = 26
    PARENT_TYPE = 27
    ELEMENT_NAME = 28
    GUI_ELEMENT_TYPE = 29
    PROPERTY = 30
    ITEM_ID = 31
    NUM_NAMES = 32
    UNKNOWN = 33
    _TRANSMISSION_DATA_TYPE = np.uint16


class PropertyType(Enum):
    LINE_WIDTH = 0
    ALPHA = 1
    Z_OFFSET = 2
    TRANSFORM = 3
    NAME = 4
    DISTANCE_FROM = 5
    LINE_STYLE = 6
    COLOR = 7
    EDGE_COLOR = 8
    FACE_COLOR = 9
    COLOR_MAP = 10
    POINT_SIZE = 11
    BUFFER_SIZE = 12
    SCATTER_STYLE = 13
    PROPERTY_FLAG = 14
    ITEM_ID = 15
    UNKNOWN = 16
    _TRANSMISSION_DATA_TYPE = np.uint8


class Function(Enum):
    DRAW_LINE3D = 0
    DRAW_ARROW = 1
    PLANE_XY = 2
    PLANE_XZ = 3
    PLANE_YZ = 4
    GRID_ON = 5
    GRID_OFF = 6
    PLOT2 = 7
    PLOT3 = 8
    REAL_TIME_PLOT = 9
    CUBE = 10
    SPHERE = 11
    PROPERTIES_EXTENSION = 12
    PROPERTIES_EXTENSION_MULTIPLE = 13
    LINE_COLLECTION2 = 14
    LINE_COLLECTION3 = 15
    STEM = 16
    FAST_PLOT2 = 17
    FAST_PLOT3 = 18
    PLOT_COLLECTION2 = 19
    PLOT_COLLECTION3 = 20
    SET_CURRENT_ELEMENT = 21
    CREATE_NEW_ELEMENT = 22
    DELETE_PLOT_OBJECT = 23
    CURRENT_ELEMENT_AS_IMAGE_VIEW = 24
    OPEN_PROJECT_FILE = 25
    NEW_ELEMENT = 26
    WAIT_FOR_FLUSH = 27
    FLUSH_ELEMENT = 28
    FLUSH_MULTIPLE_ELEMENTS = 29
    SCATTER2 = 30
    SCATTER3 = 31
    QUIVER = 32
    QUIVER3 = 33
    DRAW_LINE_BETWEEN_POINTS_3D = 34
    POLYGON_FROM_4_POINTS = 35
    DRAW_TRIANGLES_3D = 36
    DRAW_TRIANGLE_3D = 37
    DRAW_TILES = 38
    DRAW_MESH = 39
    DRAW_MESH_SEPARATE_VECTORS = 40
    HOLD_ON = 41
    HOLD_OFF = 42
    POSITION = 43
    SURF = 44
    IM_SHOW = 45
    DISABLE_AXES_FROM_MIN_MAX = 46
    SET_AXES_BOX_SCALE_FACTOR = 47
    SET_TITLE = 48
    SET_OBJECT_TRANSFORM = 49
    IS_BUSY_RENDERING = 50
    GLOBAL_ILLUMINATION = 51
    AXES_2D = 52
    AXES_3D = 53
    VIEW = 54
    CLEAR = 55
    SOFT_CLEAR = 56
    STAIRS = 57
    SHOW_LEGEND = 58
    DISABLE_SCALE_ON_ROTATION = 59
    AXES_SQUARE = 60
    UNKNOWN = 61
    _TRANSMISSION_DATA_TYPE = np.uint8


class DataType(Enum):
    FLOAT = 0
    DOUBLE = 1
    INT8 = 2
    INT16 = 3
    INT32 = 4
    INT64 = 5
    UINT8 = 6
    UINT16 = 7
    UINT32 = 8
    UINT64 = 9
    UNKNOWN = 10
    _TRANSMISSION_DATA_TYPE = np.uint8


class DataStructure(Enum):
    MATRIX = 0
    VECTOR = 1
    IMAGE = 2
    TEXT = 3
    UNKNOWN = 4
    _TRANSMISSION_DATA_TYPE = np.uint8


class ColorMapType(Enum):
    JET = 0
    HSV = 1
    MAGMA = 2
    VIRIDIS = 3
    UNKNOWN = 4
    _TRANSMISSION_DATA_TYPE = np.uint8


class ElementType(Enum):
    PLOT = 0
    IMAGE = 1
    WORLD_3D = 2
    BUTTON = 3
    TEXT_FIELD = 4
    UNKNOWN = 5
    _TRANSMISSION_DATA_TYPE = np.uint8


class ElementParent(Enum):
    TAB = 0
    WINDOW = 1
    UNKNOWN = 2
    _TRANSMISSION_DATA_TYPE = np.uint8

class PropertyFlag(Enum):
    PERSISTENT = 0
    APPENDABLE = 1
    INTERPOLATE_COLORMAP = 2
    UPDATABLE = 3
    FAST_PLOT = 4
    EXCLUDE_FROM_SELECTION = 5
    UNKNOWN = 6
    _TRANSMISSION_DATA_TYPE = np.uint8
