#ifndef DUOPLOT_CONSTANTS_H
#define DUOPLOT_CONSTANTS_H

#include <limits.h>
#include <stdint.h>

#define DUOPLOT_GUI_TCP_PORT_NUM 9758U
#define DUOPLOT_MAX_NUM_FUNCTION_HEADER_BYTES SCHAR_MAX
#define DUOPLOT_MAX_NUM_HEADER_OBJECTS 30U
#define DUOPLOT_MAGIC_NUMBER 0xDEADBEEFCAFEBABEU
#define DUOPLOT_TCP_PORT_NUM 9755U

#endif  // DUOPLOT_CONSTANTS_H
