#ifndef MAIN_APPLICATION_EVENTS_H_
#define MAIN_APPLICATION_EVENTS_H_

#include <wx/wx.h>

wxDECLARE_EVENT(EDIT_EVENT, wxCommandEvent);
wxDECLARE_EVENT(NO_ELEMENT_SELECTED, wxCommandEvent);
wxDECLARE_EVENT(CHILD_WINDOW_IN_FOCUS_EVENT, wxCommandEvent);
wxDECLARE_EVENT(NEW_EVENT, wxCommandEvent);

namespace dvs_ids
{
enum DvsIds : uint16_t
{
    EDITING_DONE = wxID_HIGHEST,
    ADD_TAB,
    EDIT_LAYOUT,
    PREFERENCES,
    SHOW_MAIN_WINDOW,
    TOGGLE_WINDOW_VISIBILITY,
    EDIT_WINDOW_NAME,
    DELETE_WINDOW,
    NEW_WINDOW,
    NEW_TAB,
    NEW_ELEMENT,
    NEW_SLIDER,
    NEW_LIST_BOX,
    NEW_EDITABLE_TEXT,
    NEW_DROP_DOWN_MENU,
    NEW_RADIO_BUTTON_GROUP,
    NEW_PLOT_PANE,
    NEW_BUTTON,
    NEW_CHECK_BOX,
    NEW_TEXT_LABEL,
    EDIT_ELEMENT_NAME,
    DELETE_ELEMENT,
    TOGGLE_PROJECTION_MODE,
    TOGGLE_TO_ZOOM,
    TOGGLE_TO_PAN,
    TOGGLE_TO_ROTATE,
    TOGGLE_TO_SELECT,
    RAISE_ELEMENT,
    LOWER_ELEMENT,
    EDIT_TAB_NAME,
    DELETE_TAB,
    PRINT_GUI_CODE,
    WINDOW_TOGGLE = wxID_HIGHEST + 1000,
    NEW_EVENT_ID
};

}

#endif  // MAIN_APPLICATION_EVENTS_H_
