#ifndef MAIN_APPLICATION_OPENGL_LOW_LEVEL_DATA_STRUCTURES_H_
#define MAIN_APPLICATION_OPENGL_LOW_LEVEL_DATA_STRUCTURES_H_

#include "misc/color_map.h"

using RGBTripletf = RGBTriplet<float>;

#endif // MAIN_APPLICATION_OPENGL_LOW_LEVEL_DATA_STRUCTURES_H_
